name: Actualizar a AWS
on:
  push:
    branches: [ "main" ] 

jobs:
  desplegar:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse v√≠a Proxy (VM1) a VM2 y desplegar
        uses: appleboy/ssh-action@master
        with:
         # VM2
          host: ${{ secrets.HOST_DNS }}       
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}          
          
         # VM1
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY }}   
        
          script: |
            cd /home/ubuntu/reserva-polideportivo-frontend
            git pull origin main
            docker stop reserva-app || true
            docker rm reserva-app || true
            docker build -t reserva-app .
            docker run -d -p 80:80 --name reserva-app reserva-app
