name: Actualizar a AWS
on:
  push:
    branches: [ "main" ] 

jobs:
  desplegar:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse por SSH y actualizar web
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/mi-web
            git pull origin main
            docker stop reserva-app || true
            docker rm reserva-app || true
            docker build -t reserva-app .
            docker run -d -p 8080:80 --name reserva-app reserva-app
